[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CRpaic C Library"
authors = [{name = "Abrantes AraÃºjo Silva Filho", email = "abrantesasf@computacaoraiz.com.br"}]
dynamic = ["version", "description"]
